server:
  port: 8088
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: order_user
    password: order_password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql.init.mode: always
  kafka:
    bootstrap-servers: localhost:9092
    topic: order
  cloud:
    stream:
      function:
        definition: transactionEventConsumer;orderCreatedEventPublisher
      bindings:
        transactionEventConsumer-in-0:
          destination: transactions
        orderCreatedEventPublisher-out-0:
          destination: orders
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

