spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/skillbox/api/order/**
          filters:
            - RewritePath=/skillbox(?<segment>/?.*), $\{segment}
  application:
    name: gateway
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.gateway: TRACE

