scrape_configs:
  - job_name: 'MyAppMetrics'
    scrape_interval: 3s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8080']
        labels:
          instance: 'order-service:8080'
          application: 'MyApp'
